### ISSUE TITLE
Не удаётся собрать под Debian

### ISSUE THREAD

**Issue by 1int** [mamchits/phantom#6]
Не удаётся собрать под Debian
Linux 2.6.32-5-amd64 #1 SMP x86_64 GNU/Linux

``` shell

 git clone git://github.com/mamchits/phantom.git
cd phantom
make all
```

`opts.mk:2: *** missing -R make option.  Stop.`

``` shell
make -R all
```

`<.....>
pd/debug/addrinfo_bfd.C:13:17: error: bfd.h: No such file or directory`

Если вручную добавить недостающий bfd.h, сыпятся другие ошибки, связанные с нехваткой ansidecl.h. Если добавить его, всё равно компиляция проваливается.

Хэлп нидед.

**Comment by mamchits** [comment]
On 2013-01-18 13:11, Pavel wrote:

> Не удаётся собрать под Debian
> Linux 2.6.32-5-amd64 #1 https://github.com/mamchits/phantom/issues/1 SMP x86_64 GNU/Linux
> 
>  git clone git://github.com/mamchits/phantom.git
> cd phantom
> make all
> 
> |opts.mk:2: **\* missing -R make option. Stop.|
> 
> make -R all
> 
> |<.....>
> pd/debug/addrinfo_bfd.C:13:17: error: bfd.h: No such file or directory|
> 
> Если вручную добавить недостающий bfd.h, сыпятся другие ошибки, связанные с нехваткой ansidecl.h. Если добавить его, всё равно компиляция проваливается.
> 
> Хэлп нидед.

Там же есть binutils-dev в build-depends. Надо поставить.

> —
> Reply to this email directly or view it on GitHub https://github.com/mamchits/phantom/issues/6.

## 

Eugene Mamchits
Старший разработчик
